export type Status = 'On Track' | 'At Risk' | 'Delayed' | 'Blocked' | 'Completed' | 'Open' | 'Verified' | 'Rejected' | 'Escalated'
export type Activity = { id: string; activity: string; discipline: string; level: string; planned: number; actual: number; status: Status; risk: string; owner: string; plannedFinish?: string; float?: number; successors?: string[]; milestoneId?: string; critical?: boolean }
export type Project = { id: string; name: string; client: string; location: string; progress: number; status: Status }
export type Milestone = { name: string; progress: number; planned: string; forecast: string; status: Status }
export type Document = { id: string; name: string; type: string; source: string; status: string; confidence: number }
export type Alert = { id: string; title: string; type: string; severity: string; read: boolean }
export type Contradiction = { id: string; activity: string; source: string; reported: string; conflict: string; severity: string; status: string }
export const navGroups = [
  { label: 'Overview', items: [['Overview', '/dashboard', 'LayoutDashboard']] },
  { label: 'Control Tower', items: [['Project Health', '/project-health', 'Activity'], ['Critical Path', '/critical-path', 'Route'], ['Milestones', '/milestones', 'Flag']] },
  { label: 'Project', items: [['Projects', '/projects', 'BriefcaseBusiness'], ['Activities', '/activities', 'ListChecks'], ['Schedule', '/schedule', 'CalendarRange']] },
  { label: 'Data Hub', items: [['Documents', '/documents', 'FileText'], ['Site Photos', '/site-photos', 'Camera'], ['Voice Updates', '/voice-updates', 'Mic'], ['Data Sources', '/data-sources', 'Database']] },
  { label: 'AI Intelligence', items: [['Contradictions', '/contradictions', 'GitCompare'], ['Activity Discovery', '/activity-discovery', 'Sparkles'], ['Delay Intelligence', '/delay-intelligence', 'Timer'], ['Root Cause', '/root-cause', 'GitBranch'], ['Evidence', '/evidence', 'FileSearch']] },
  { label: 'Decision Center', items: [['Alerts', '/alerts', 'BellRing'], ['Recommendations', '/recommendations', 'Lightbulb'], ['Impact Propagation', '/impact-propagation', 'Network'], ['What-If Simulator', '/what-if', 'Shuffle'], ['Recovery Plans', '/recovery-plans', 'ClipboardCheck']] },
  { label: 'AI Copilot', items: [['AI Copilot', '/copilot', 'Bot']] },
  { label: 'Reports', items: [['Daily Reports', '/reports/daily', 'FileBarChart'], ['Weekly Reports', '/reports/weekly', 'CalendarDays'], ['Analytics', '/reports/analytics', 'ChartNoAxesCombined']] },
  { label: 'Admin', items: [['Users & Roles', '/admin/users', 'UsersRound'], ['Audit Trail', '/admin/audit-trail', 'History'], ['Settings', '/admin/settings', 'Settings2']] },
]
export const activities: Activity[] = [
  { id: 'PIP-L5-0241', activity: 'Pipe Installation - Line 24-XX', discipline: 'Piping', level: 'L5', planned: 100, actual: 80, status: 'Delayed', risk: 'High', owner: 'A. Sharma', plannedFinish: '10 Jun 2026', float: 0, successors: ['PIP-L5-0242'], milestoneId: 'MS-PIP', critical: true },
  { id: 'PIP-L5-0242', activity: 'Welding - Line 24-XX', discipline: 'Piping', level: 'L5', planned: 72, actual: 48, status: 'At Risk', risk: 'High', owner: 'R. Das', plannedFinish: '15 Jun 2026', float: 2, successors: ['PIP-L6-0243'], milestoneId: 'MS-PIP', critical: true },
  { id: 'PIP-L6-0243', activity: 'NDT Inspection - Line 24-XX', discipline: 'Piping', level: 'L6', planned: 55, actual: 32, status: 'At Risk', risk: 'Medium', owner: 'P. Nair', plannedFinish: '18 Jun 2026', float: 0, successors: ['CIV-L5-0112'], milestoneId: 'MS-PIP', critical: true },
  { id: 'CIV-L5-0112', activity: 'Backfilling - Area 3', discipline: 'Civil', level: 'L5', planned: 100, actual: 85, status: 'At Risk', risk: 'Medium', owner: 'P. Nair', plannedFinish: '24 Jun 2026', float: 1, successors: ['COM-L5-0001'], milestoneId: 'MS-COM', critical: false },
  { id: 'COM-L5-0001', activity: 'Commissioning - Area 3', discipline: 'Commissioning', level: 'L5', planned: 40, actual: 20, status: 'Blocked', risk: 'Critical', owner: 'M. Khan', plannedFinish: '31 Dec 2026', float: 0, successors: [], milestoneId: 'MS-COM', critical: true },
  { id: 'ELE-L5-0087', activity: 'Cable Tray Installation - Area 3', discipline: 'Electrical', level: 'L5', planned: 65, actual: 66, status: 'On Track', risk: 'Low', owner: 'S. Roy', plannedFinish: '30 Jun 2026', float: 4, successors: [], milestoneId: 'MS-ELE', critical: false },
  { id: 'INS-L6-0192', activity: 'Instrument Calibration - PT-204', discipline: 'Instrumentation', level: 'L6', planned: 40, actual: 20, status: 'Blocked', risk: 'Critical', owner: 'M. Khan', plannedFinish: '08 Jul 2026', float: 3, successors: [], milestoneId: 'MS-COM', critical: false },
]
export const projects: Project[] = [{ id: 'OIL-RAJ-01', name: 'Rajasthan Gas Pipeline Expansion', client: 'OIL India', location: 'Rajasthan', progress: 67.8, status: 'At Risk' }, { id: 'OIL-ASM-02', name: 'Assam Production Facility Upgrade', client: 'OIL India', location: 'Assam', progress: 52, status: 'On Track' }, { id: 'OIL-OFF-03', name: 'Offshore Development Package', client: 'OIL India', location: 'Arabian Sea', progress: 41, status: 'At Risk' }]
export const milestones: Milestone[] = [{ name: 'Engineering', progress: 100, planned: '12 Apr 2026', forecast: '12 Apr 2026', status: 'Completed' }, { name: 'Procurement', progress: 88, planned: '28 Jun 2026', forecast: '02 Jul 2026', status: 'At Risk' }, { name: 'Civil Works', progress: 79, planned: '14 Jul 2026', forecast: '18 Jul 2026', status: 'At Risk' }, { name: 'Piping', progress: 64, planned: '30 Aug 2026', forecast: '12 Sep 2026', status: 'Delayed' }, { name: 'Mechanical', progress: 66, planned: '18 Sep 2026', forecast: '21 Sep 2026', status: 'On Track' }, { name: 'Commissioning', progress: 24, planned: '31 Dec 2026', forecast: '31 Dec 2026', status: 'On Track' }]
export const documents: Document[] = [{ id: 'DOC-00326', name: 'Daily Progress Report - Area 3', type: 'PDF', source: 'Contractor Report', status: 'Planner Review', confidence: 92 }, { id: 'DOC-00325', name: 'Weekly Progress Report W22', type: 'PDF', source: 'Daily Reports', status: 'Completed', confidence: 98 }, { id: 'DOC-00324', name: 'Baseline Schedule v3.2', type: 'XLSX', source: 'Schedule Export', status: 'Completed', confidence: 100 }]
export const alerts: Alert[] = [{ id: 'ALT-018', title: 'Line 24-XX is 20% behind plan', type: 'Critical Delay', severity: 'Critical', read: false }, { id: 'ALT-017', title: 'Contradiction requires planner review', type: 'Contradiction', severity: 'High', read: false }, { id: 'ALT-016', title: 'Temporary access road detected', type: 'New Activity', severity: 'Medium', read: true }]
export const contradictions: Contradiction[] = [{ id: 'CON-012', activity: 'PIP-L5-0241 / Erect Line 24-XX', source: 'Daily Report vs Excel', reported: '100% complete', conflict: '80% complete; welding pending', severity: 'High', status: 'Open' }, { id: 'CON-011', activity: 'CIV-L5-0112 / Foundation F-204', source: 'Voice vs Schedule', reported: '85% complete', conflict: 'Inspection not signed off', severity: 'Medium', status: 'Open' }]
export const progressData = [{ period: 'W1', planned: 48, actual: 45 }, { period: 'W2', planned: 52, actual: 50 }, { period: 'W3', planned: 56, actual: 54 }, { period: 'W4', planned: 60, actual: 58 }, { period: 'W5', planned: 64, actual: 61 }, { period: 'W6', planned: 68, actual: 64 }, { period: 'W7', planned: 71, actual: 68 }]
export const disciplineData = [{ name: 'Civil', planned: 82, actual: 79 }, { name: 'Piping', planned: 71, actual: 64 }, { name: 'Mechanical', planned: 68, actual: 66 }, { name: 'Electrical', planned: 74, actual: 72 }, { name: 'Instrumentation', planned: 61, actual: 59 }, { name: 'HSE', planned: 91, actual: 94 }]
export const riskData = [{ name: 'Low', value: 52, color: '#279b72' }, { name: 'Medium', value: 29, color: '#d49a2f' }, { name: 'High', value: 14, color: '#e07152' }, { name: 'Critical', value: 5, color: '#c74343' }]
export const delayTrend = [{ period: 'May 06', delayed: 32 }, { period: 'May 13', delayed: 36 }, { period: 'May 20', delayed: 41 }, { period: 'May 27', delayed: 38 }, { period: 'Jun 03', delayed: 47 }]
